"""Tambah kolom jumlah_alpa ke rekap_buku_sadar

Revision ID: 102bb87973dc
Revises: 3eb607f82e7a
Create Date: 2025-08-02 01:37:09.475445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102bb87973dc'
down_revision = '3eb607f82e7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_alpa', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('jumlah_telat', sa.Integer(), nullable=True))
        batch_op.drop_column('keterangan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('jumlah_telat')
        batch_op.drop_column('jumlah_alpa')

    # ### end Alembic commands ###
