"""Add kategori to Santri model

Revision ID: 13eb2d4abddf
Revises: 274b26ec429f
Create Date: 2025-07-15 00:13:43.432281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13eb2d4abddf'
down_revision = '274b26ec429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kategori', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('kategori')

    # ### end Alembic commands ###
