"""Add ON DELETE CASCADE to foreign keys

Revision ID: 25698cd24276
Revises: 59fcafd44c40
Create Date: 2025-07-19 13:39:55.931333

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25698cd24276'
down_revision = '59fcafd44c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Langkah 1: Tambahkan kolom 'role' TAPI biarkan boleh kosong untuk sementara
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))

    # Langkah 2: Isi semua baris yang sudah ada dengan nilai default 'admin'
    op.execute("UPDATE \"user\" SET role = 'admin' WHERE role IS NULL")

    # Langkah 3: Sekarang, ubah kolom 'role' menjadi WAJIB DIISI (NOT NULL)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role', existing_type=sa.String(length=20), nullable=False)

    # Bagian untuk memperbarui Foreign Keys (biarkan seperti aslinya)
    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.drop_constraint('rekap_absensi_santri_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('rekap_absensi_santri_id_fkey', 'santri', ['santri_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.drop_constraint('rekap_buku_sadar_santri_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('rekap_buku_sadar_santri_id_fkey', 'santri', ['santri_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('rekap_sks', schema=None) as batch_op:
        batch_op.drop_constraint('rekap_sks_santri_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('rekap_sks_santri_id_fkey', 'santri', ['santri_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('rekap_sks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rekap_sks_santri_id_fkey'), 'santri', ['santri_id'], ['id'])

    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rekap_buku_sadar_santri_id_fkey'), 'santri', ['santri_id'], ['id'])

    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('rekap_absensi_santri_id_fkey'), 'santri', ['santri_id'], ['id'])

    # ### end Alembic commands ###
