"""Create all tables from scratch

Revision ID: 3eb607f82e7a
Revises: 
Create Date: 2025-07-31 02:08:57.421699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb607f82e7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Step 1: Add the new columns, but allow them to be empty for now (nullable=True)
    op.add_column('rekap_absensi', sa.Column('riyadhoh', sa.String(length=255), nullable=True))
    op.add_column('rekap_absensi', sa.Column('status_lunas', sa.String(length=20), nullable=True))

    # Step 2: Fill all existing rows in the new 'status_lunas' column with a default value
    op.execute("UPDATE rekap_absensi SET status_lunas = 'Belum Lunas' WHERE status_lunas IS NULL")

    # Step 3: Now that there are no empty rows, change the 'status_lunas' column to be required (nullable=False)
    op.alter_column('rekap_absensi', 'status_lunas',
                  existing_type=sa.VARCHAR(length=20),
                  nullable=False)

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('jumlah_telat')
        batch_op.drop_column('jumlah_alpa')

    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.drop_column('status_lunas')
        batch_op.drop_column('riyadhoh')

    # ### end Alembic commands ###
