"""Initial migration with all tables

Revision ID: 3f4a0bc31fdc
Revises: 
Create Date: 2025-07-12 13:05:07.655344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4a0bc31fdc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sks_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_sks', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_sks')
    )
    op.create_table('rekap_sks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('sks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.ForeignKeyConstraint(['sks_id'], ['sks_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekap_sks')
    op.drop_table('sks_master')
    op.drop_table('santri')
    # ### end Alembic commands ###
