"""Initial migration for PostgreSQL

Revision ID: 59fcafd44c40
Revises: 
Create Date: 2025-07-15 02:15:21.123272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fcafd44c40'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('santri',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=255), nullable=True),
    sa.Column('nama_orang_tua', sa.String(length=100), nullable=True),
    sa.Column('nama_pembimbing', sa.String(length=100), nullable=True),
    sa.Column('kelas_saat_ini', sa.String(length=50), nullable=True),
    sa.Column('kelas_sekolah', sa.String(length=50), nullable=True),
    sa.Column('kamar', sa.String(length=50), nullable=True),
    sa.Column('no_wa_wali', sa.String(length=20), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sks_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_sks', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nama_sks')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('rekap_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah_hadir', sa.Integer(), nullable=False),
    sa.Column('jumlah_sakit_izin', sa.Integer(), nullable=False),
    sa.Column('jumlah_alpa', sa.Integer(), nullable=False),
    sa.Column('keterangan_mingguan', sa.String(length=255), nullable=True),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rekap_buku_sadar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('tanggal_awal_minggu', sa.Date(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('riyadhoh', sa.String(length=255), nullable=True),
    sa.Column('status_lunas', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('santri_id', 'tanggal_awal_minggu', name='_santri_minggu_uc')
    )
    op.create_table('rekap_sks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.Column('sks_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.ForeignKeyConstraint(['sks_id'], ['sks_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekap_sks')
    op.drop_table('rekap_buku_sadar')
    op.drop_table('rekap_absensi')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('sks_master')
    op.drop_table('santri')
    # ### end Alembic commands ###
