"""Add new columns to Santri table

Revision ID: 762f1b60a699
Revises: 3f4a0bc31fdc
Create Date: 2025-07-12 13:20:31.141741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '762f1b60a699'
down_revision = '3f4a0bc31fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nama_orang_tua', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nama_pembimbing', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('kelas_saat_ini', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('kelas_sekolah', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('kamar', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('kamar')
        batch_op.drop_column('kelas_sekolah')
        batch_op.drop_column('kelas_saat_ini')
        batch_op.drop_column('nama_pembimbing')
        batch_op.drop_column('nama_orang_tua')

    # ### end Alembic commands ###
