"""ubah rekap buku sadar

Revision ID: 774bc5e79b09
Revises: 8eb7e300c9b7
Create Date: 2025-07-14 00:01:54.318800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '774bc5e79b09'
down_revision = '8eb7e300c9b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_pelanggaran', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('keterangan_bulanan', sa.String(length=255), nullable=True))
        batch_op.drop_column('jumlah')
        batch_op.drop_column('keterangan')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keterangan', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('jumlah', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('keterangan_bulanan')
        batch_op.drop_column('jumlah_pelanggaran')

    # ### end Alembic commands ###
