"""ubah rekap absensi

Revision ID: 8eb7e300c9b7
Revises: a82770592d4a
Create Date: 2025-07-13 23:06:49.657148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8eb7e300c9b7'
down_revision = 'a82770592d4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jumlah_hadir', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jumlah_sakit_izin', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jumlah_alpa', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('keterangan_mingguan', sa.String(length=255), nullable=True))
        batch_op.drop_column('keterangan')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_absensi', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('keterangan', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('keterangan_mingguan')
        batch_op.drop_column('jumlah_alpa')
        batch_op.drop_column('jumlah_sakit_izin')
        batch_op.drop_column('jumlah_hadir')

    # ### end Alembic commands ###
