"""nambah buku sadar

Revision ID: a3496532a22f
Revises: dbb642679beb
Create Date: 2025-07-12 14:00:29.931305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3496532a22f'
down_revision = 'dbb642679beb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekap_buku_sadar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('jumlah', sa.Integer(), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('riyadhoh', sa.String(length=255), nullable=True),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekap_buku_sadar')
    # ### end Alembic commands ###
