"""add nomor wali

Revision ID: a82770592d4a
Revises: e35b9ee3c53f
Create Date: 2025-07-12 21:12:12.735020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82770592d4a'
down_revision = 'e35b9ee3c53f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_wa_wali', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('santri', schema=None) as batch_op:
        batch_op.drop_column('no_wa_wali')

    # ### end Alembic commands ###
