"""Re-overhaul RekapBukuSadar to weekly summary

Revision ID: a84b6d195039
Revises: 774bc5e79b09
Create Date: 2025-07-14 03:12:29.000436

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'a84b6d195039'
down_revision = '774bc5e79b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### KODE YANG SUDAH DIPERBAIKI ###

    # Hapus tabel lama untuk memastikan kita mulai dari awal yang bersih
    op.drop_table('rekap_buku_sadar')

    # Buat kembali tabel dengan skema yang benar dari awal
    op.create_table('rekap_buku_sadar',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('santri_id', sa.Integer(), nullable=False),
        sa.Column('tanggal_awal_minggu', sa.Date(), nullable=False),
        sa.Column('keterangan', sa.String(length=255), nullable=True),
        sa.Column('riyadhoh', sa.String(length=255), nullable=True),
        sa.Column('status_lunas', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('santri_id', 'tanggal_awal_minggu', name='_santri_minggu_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.drop_constraint('_santri_minggu_uc', type_='unique')

    # ### end Alembic commands ###
