"""Add RekapAbsensi table

Revision ID: dbb642679beb
Revises: 762f1b60a699
Create Date: 2025-07-12 13:55:09.205616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb642679beb'
down_revision = '762f1b60a699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rekap_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('santri_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['santri_id'], ['santri.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rekap_absensi')
    # ### end Alembic commands ###
