"""add kolom lunas

Revision ID: e35b9ee3c53f
Revises: a3496532a22f
Create Date: 2025-07-12 14:33:29.463825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e35b9ee3c53f'
down_revision = 'a3496532a22f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_riyadhoh', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rekap_buku_sadar', schema=None) as batch_op:
        batch_op.drop_column('status_riyadhoh')

    # ### end Alembic commands ###
